/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_11711057josephmoscoso;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        inicio();
    }

    public void inicio() {
        administrarATMs a = new administrarATMs("./ATMs.atm");
        a.cargarArchivo();
//        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_atm.getModel();
        if (a.getAtm().isEmpty()) {

        } else {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (ATM t : a.getAtm()) {
                m.addElement(t);
            }
            cb_atm.setModel(m);
        }
        a.escribirArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_atm = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_fechaATM = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bt_c = new javax.swing.JButton();
        tf_ubicacion = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        mante = new javax.swing.JSpinner();
        b500 = new javax.swing.JSpinner();
        b100 = new javax.swing.JSpinner();
        jd_users = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rb_cliente = new javax.swing.JRadioButton();
        rb_mantenimiento = new javax.swing.JRadioButton();
        contra = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        fechan = new com.toedter.calendar.JDateChooser();
        fechaa = new com.toedter.calendar.JDateChooser();
        nombre2 = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        crearu = new javax.swing.JButton();
        grupo = new javax.swing.ButtonGroup();
        jd_login = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_iu = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JPasswordField();
        iniciar = new javax.swing.JButton();
        jd_cliente = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jl_hora1 = new javax.swing.JLabel();
        bt_retirarPisto = new javax.swing.JButton();
        bt_ingresar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bt_nevacuenta = new javax.swing.JButton();
        bt_revisarsaldo = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jd_mantenimiento = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        b100a = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        b500a = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jl_hora = new javax.swing.JLabel();
        bt_agregarBishete = new javax.swing.JButton();
        meter = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_cuentas = new javax.swing.JList<>();
        bt_mandarPisto = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        c100 = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        c500 = new javax.swing.JSpinner();
        jd_transacciones = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historial = new javax.swing.JList<>();
        jd_estado = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_cuentas1 = new javax.swing.JList<>();
        versaldo = new javax.swing.JButton();
        c101 = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jd_retirar = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_cuentas2 = new javax.swing.JList<>();
        bt_mandarPisto1 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        c102 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        c501 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        bt_atm = new javax.swing.JButton();
        bt_users = new javax.swing.JButton();
        cb_atm = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Creacion ATM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ubicacion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de creacion");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Mantenimiento cada cuanto semanas");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Numero Billetes 500");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Numero Billetes 100");

        bt_c.setText("Crear");
        bt_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cMouseClicked(evt);
            }
        });

        mante.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jd_atmLayout = new javax.swing.GroupLayout(jd_atm.getContentPane());
        jd_atm.getContentPane().setLayout(jd_atmLayout);
        jd_atmLayout.setHorizontalGroup(
            jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_atmLayout.createSequentialGroup()
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_atmLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_fechaATM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_ubicacion)
                            .addComponent(tf_id)
                            .addGroup(jd_atmLayout.createSequentialGroup()
                                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b500)
                                    .addComponent(mante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(b100))
                                .addGap(203, 203, 203))))
                    .addGroup(jd_atmLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel3))
                    .addGroup(jd_atmLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(bt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_atmLayout.setVerticalGroup(
            jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_atmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_fechaATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(b500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_atmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(b100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Creacion de Usuarios");

        jLabel11.setText("ID");

        jLabel12.setText("Primer nombre");

        jLabel13.setText("Segundo nombre");

        jLabel14.setText("Apellido");

        jLabel15.setText("Fecha de nacimiento");

        jLabel16.setText("Fecha de afiliacion");

        jLabel17.setText("Contraseña");

        jLabel18.setText("Tipo de usuario");

        grupo.add(rb_cliente);
        rb_cliente.setSelected(true);
        rb_cliente.setText("Cliente");

        grupo.add(rb_mantenimiento);
        rb_mantenimiento.setText("Mantenimiento");

        crearu.setText("Crear");
        crearu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_usersLayout = new javax.swing.GroupLayout(jd_users.getContentPane());
        jd_users.getContentPane().setLayout(jd_usersLayout);
        jd_usersLayout.setHorizontalGroup(
            jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usersLayout.createSequentialGroup()
                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_usersLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10))
                    .addGroup(jd_usersLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_usersLayout.createSequentialGroup()
                                .addComponent(rb_cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_mantenimiento))
                            .addComponent(contra)
                            .addComponent(apellido)
                            .addComponent(fechan, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(fechaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombre2)
                            .addComponent(nombre1)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_usersLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(crearu)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jd_usersLayout.setVerticalGroup(
            jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_usersLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_usersLayout.createSequentialGroup()
                                .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_usersLayout.createSequentialGroup()
                                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel15))
                                    .addComponent(fechan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addComponent(fechaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(rb_cliente)
                            .addComponent(rb_mantenimiento)))
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Log In");

        jLabel20.setText("ID");

        jLabel21.setText("Contraseña");

        iniciar.setText("Iniciar Sesion");
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel19))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_iu)
                            .addComponent(tf_ip, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_iu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iniciar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("ATM Cliente");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Hora actual: ");

        jl_hora1.setText("jLabel27");

        bt_retirarPisto.setText("Retirar el dinero de una cuenta");
        bt_retirarPisto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_retirarPistoMouseClicked(evt);
            }
        });

        bt_ingresar.setText("Ingresar dinero a una cuenta");
        bt_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ingresarMouseClicked(evt);
            }
        });

        jButton3.setText("Ingresar dinero a una cuenta de otra persona");

        bt_nevacuenta.setText("Crear nueva cuenta");
        bt_nevacuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_nevacuentaMouseClicked(evt);
            }
        });

        bt_revisarsaldo.setText("Revisar el estado de una cuenta");
        bt_revisarsaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_revisarsaldoMouseClicked(evt);
            }
        });

        jButton6.setText("Revisar transacciones");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_clienteLayout = new javax.swing.GroupLayout(jd_cliente.getContentPane());
        jd_cliente.getContentPane().setLayout(jd_clienteLayout);
        jd_clienteLayout.setHorizontalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_revisarsaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_nevacuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                        .addComponent(bt_ingresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_retirarPisto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_clienteLayout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jl_hora1))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jd_clienteLayout.setVerticalGroup(
            jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel27)
                    .addComponent(jl_hora1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_retirarPisto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_nevacuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_revisarsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("ATM Mantenimiento");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Cantidad de billetes de 100 a agregar");

        b100a.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Cantidad de billetes de 500 a agregar");

        b500a.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Hora actual: ");

        jl_hora.setText("jLabel27");

        bt_agregarBishete.setText("Agregar billetes");
        bt_agregarBishete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarBisheteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_mantenimientoLayout = new javax.swing.GroupLayout(jd_mantenimiento.getContentPane());
        jd_mantenimiento.getContentPane().setLayout(jd_mantenimientoLayout);
        jd_mantenimientoLayout.setHorizontalGroup(
            jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                .addGroup(jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b100a, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel23))
                    .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b500a, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_agregarBishete)
                            .addComponent(jl_hora))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_mantenimientoLayout.setVerticalGroup(
            jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(b100a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(b500a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jl_hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_agregarBishete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Ingresar dinero");

        jl_cuentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_cuentas.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_cuentas);

        bt_mandarPisto.setText("Ingresar dinero");
        bt_mandarPisto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mandarPistoMouseClicked(evt);
            }
        });

        jLabel29.setText("100L(cantidad)");

        c100.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel30.setText("500L(cantidad)");

        c500.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout meterLayout = new javax.swing.GroupLayout(meter.getContentPane());
        meter.getContentPane().setLayout(meterLayout);
        meterLayout.setHorizontalGroup(
            meterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterLayout.createSequentialGroup()
                .addGroup(meterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(meterLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel28))
                    .addGroup(meterLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(meterLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(bt_mandarPisto)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(meterLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        meterLayout.setVerticalGroup(
            meterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(meterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(c100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(meterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(c500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bt_mandarPisto)
                .addContainerGap())
        );

        jd_transacciones.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jd_transaccionesWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_transaccionesWindowClosing(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Historial transaccion");

        historial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        historial.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(historial);

        javax.swing.GroupLayout jd_transaccionesLayout = new javax.swing.GroupLayout(jd_transacciones.getContentPane());
        jd_transacciones.getContentPane().setLayout(jd_transaccionesLayout);
        jd_transaccionesLayout.setHorizontalGroup(
            jd_transaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_transaccionesLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_transaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jd_transaccionesLayout.setVerticalGroup(
            jd_transaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_transaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Ver saldo");

        jl_cuentas1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_cuentas1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_cuentas1);

        versaldo.setText("Ver saldo");
        versaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                versaldoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_estadoLayout = new javax.swing.GroupLayout(jd_estado.getContentPane());
        jd_estado.getContentPane().setLayout(jd_estadoLayout);
        jd_estadoLayout.setHorizontalGroup(
            jd_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estadoLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jd_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(versaldo)
                    .addComponent(jLabel32))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(jd_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_estadoLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );
        jd_estadoLayout.setVerticalGroup(
            jd_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(versaldo)
                .addGap(30, 30, 30))
            .addGroup(jd_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_estadoLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );

        c101.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel33.setText("500L(cantidad)");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Retirar dinero");

        jl_cuentas2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_cuentas2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_cuentas2);

        bt_mandarPisto1.setText("Retirar");
        bt_mandarPisto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mandarPisto1MouseClicked(evt);
            }
        });

        jLabel35.setText("100L(cantidad)");

        c102.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel36.setText("500L(cantidad)");

        c501.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jd_retirarLayout = new javax.swing.GroupLayout(jd_retirar.getContentPane());
        jd_retirar.getContentPane().setLayout(jd_retirarLayout);
        jd_retirarLayout.setHorizontalGroup(
            jd_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_retirarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c501, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jd_retirarLayout.createSequentialGroup()
                .addGroup(jd_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_retirarLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel34))
                    .addGroup(jd_retirarLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_retirarLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(bt_mandarPisto1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jd_retirarLayout.setVerticalGroup(
            jd_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_retirarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(c102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(c501, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_mandarPisto1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ATM Master Race");

        bt_atm.setText("Crear ATM");
        bt_atm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_atmMouseClicked(evt);
            }
        });

        bt_users.setText("Crear usuario");
        bt_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_usersMouseClicked(evt);
            }
        });

        cb_atm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cb_atm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_atmItemStateChanged(evt);
            }
        });

        jLabel2.setText("ATMs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_atm)
                                .addGap(61, 61, 61)
                                .addComponent(bt_users))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(cb_atm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_atm)
                    .addComponent(bt_users))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_atm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_atmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_atmMouseClicked
        // TODO add your handling code here:
        try {
            jd_atm.setModal(true);
            jd_atm.pack();
            jd_atm.setLocationRelativeTo(this);
            jd_atm.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_atmMouseClicked

    private void bt_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_usersMouseClicked
        // TODO add your handling code here:
        try {
            jd_users.setModal(true);
            jd_users.pack();
            jd_users.setLocationRelativeTo(this);
            jd_users.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_usersMouseClicked

    private void bt_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cMouseClicked
        // TODO add your handling code here:
        try {
            administrarATMs a = new administrarATMs("./ATMs.atm");
            a.cargarArchivo();
            boolean e = true;
            for (ATM t : a.getAtm()) {
                if (Integer.parseInt(tf_id.getText()) == t.getId()) {
                    e = false;
                }
            }
            if (e == true) {
                DateFormat f = new SimpleDateFormat("dd/MM/YYYY");
                ATM nuevo = new ATM(tf_ubicacion.getText(), Integer.parseInt(tf_id.getText()), f.format(tf_fechaATM.getDate()), (int) mante.getValue(), (int) b500.getValue(), (int) b100.getValue());
                a.getAtm().add(nuevo);
                JOptionPane.showMessageDialog(jd_atm, "ATM creado con exito");
                jd_atm.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(jd_atm, "Error, ID repetido");
            }
            a.escribirArchivo();
            inicio();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_atm, "Error, dato incorrecto");
        }
    }//GEN-LAST:event_bt_cMouseClicked

    private void crearuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearuMouseClicked
        // TODO add your handling code here:
        try {
            AdminUsuarios a = new AdminUsuarios("./Users.u");
            a.cargarArchivo();
            boolean e = true;
            for (Usuarios t : a.getUsers()) {
                if (Integer.parseInt(id.getText()) == t.getIduser()) {
                    e = false;
                }
            }
            if (e == true) {
                DateFormat f = new SimpleDateFormat("dd/MM/YYYY");
                if (rb_cliente.isSelected()) {
                    Cliente cc = new Cliente(Integer.parseInt(id.getText()), nombre1.getText(), nombre2.getText(), apellido.getText(), f.format(fechan.getDate()), f.format(fechaa.getDate()), contra.getText());
                    a.getUsers().add(cc);
                    JOptionPane.showMessageDialog(jd_users, "Usuario cliente creado con exito");
                    jd_users.setVisible(false);
                } else {
                    Mantenimiento cc = new Mantenimiento(Integer.parseInt(id.getText()), nombre1.getText(), nombre2.getText(), apellido.getText(), f.format(fechan.getDate()), f.format(fechaa.getDate()), contra.getText());
                    a.getUsers().add(cc);
                    JOptionPane.showMessageDialog(jd_users, "Usuario mantenimiento creado con exito");
                    jd_users.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(jd_users, "Error ID repetido");
            }
            a.escribirArchivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_users, "Error, dato incorrecto");
        }
    }//GEN-LAST:event_crearuMouseClicked

    private void cb_atmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_atmItemStateChanged
        // TODO add your handling code here:
        try {
            if (cb_atm.getSelectedIndex() >= 0) {
                jd_login.setModal(true);
                jd_login.pack();
                jd_login.setLocationRelativeTo(this);
                jd_login.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cb_atmItemStateChanged

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        // TODO add your handling code here:
        try {
            AdminUsuarios a = new AdminUsuarios("./Users.u");
            a.cargarArchivo();
            if (c < 5) {
                boolean e = false, cc = true, m = true;
                for (Usuarios t : a.getUsers()) {
                    if (tf_iu.getText().equals(Integer.toString(t.getIduser())) && tf_ip.getText().equals(t.getContraseña())) {
                        e = true;
                        if (t instanceof Cliente) {
//                            cc = true;
                            // m = false;
                            HiloHora h = new HiloHora(jl_hora1);
                            h.start();
                            jd_cliente.setModal(true);
                            jd_cliente.pack();
                            jd_cliente.setLocationRelativeTo(this);
                            jd_cliente.setVisible(true);
                        }
                        if (t instanceof Mantenimiento) {
                            //m = true;
//                            cc = false;
                            HiloHora h = new HiloHora(jl_hora);
                            h.start();
                            jd_mantenimiento.setModal(true);
                            jd_mantenimiento.pack();
                            jd_mantenimiento.setLocationRelativeTo(this);
                            jd_mantenimiento.setVisible(true);
                        }
                    }
                }
                if (e == true) {
//                    if (cc = true) {
//                        jd_cliente.setModal(true);
//                        jd_cliente.pack();
//                        jd_cliente.setLocationRelativeTo(this);
//                        jd_cliente.setVisible(true);
//                    }
//                    if (cc == false) {
//                        jd_mantenimiento.setModal(true);
//                        jd_mantenimiento.pack();
//                        jd_mantenimiento.setLocationRelativeTo(this);
//                        jd_mantenimiento.setVisible(true);
//                    }
                } else {
                    JOptionPane.showMessageDialog(jd_login, "Error, datos incorrectos o usuario no existe");
                    c++;
                }
            } else {
                JOptionPane.showMessageDialog(jd_login, "Numero de intentos alcanzado, el sistema sera bloqueado");
                tf_iu.setEditable(false);
                tf_ip.setEditable(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_login, "Error fatal");
        }
    }//GEN-LAST:event_iniciarMouseClicked

    private void bt_agregarBisheteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarBisheteMouseClicked
        // TODO add your handling code here:
        try {
            administrarATMs a = new administrarATMs("./ATMs.atm");
            a.cargarArchivo();
            a.getAtm().get(cb_atm.getSelectedIndex()).setDen100(a.getAtm().get(cb_atm.getSelectedIndex()).getDen100() + (int) b100a.getValue());
            a.getAtm().get(cb_atm.getSelectedIndex()).setDen500(a.getAtm().get(cb_atm.getSelectedIndex()).getDen500() + (int) b100a.getValue());
            a.escribirArchivo();
            inicio();
            JOptionPane.showMessageDialog(jd_mantenimiento, "dinero agregado con exito");
            jd_mantenimiento.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_agregarBisheteMouseClicked

    private void bt_nevacuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_nevacuentaMouseClicked
        // TODO add your handling code here:
        try {
            int cuenta = Integer.parseInt(JOptionPane.showInputDialog(jd_cliente, "Ingrese el número de cuenta"));
            AdminUsuarios a = new AdminUsuarios("./Users.u");
            a.cargarArchivo();
            boolean e = true;
            int cc = 0, ccc = 0;
            for (int i = 0; i < a.getUsers().size(); i++) {
                if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                    for (int j = 0; j < ((Cliente) a.getUsers().get(i)).getCuentas().size(); j++) {
                        if (cuenta == ((Cliente) a.getUsers().get(i)).getCuentas().get(j).getIdPropietario()) {
                            cc = i;
                            ccc = j;
                            e = false;
                        }
                    }
                }
            }
            if (e == true) {
                ((Cliente) a.getUsers().get(cc)).getCuentas().add(new Cuenta(cuenta, 0, Integer.parseInt(tf_iu.getText())));
                JOptionPane.showMessageDialog(jd_cliente, "Transaccion exitosa");
                jd_cliente.setVisible(false);
                a.escribirArchivo();
            } else {
                JOptionPane.showMessageDialog(jd_cliente, "Transaccion incorrecto, cuenta repetida");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_cliente, "Error, dato incorrecto");
        }
    }//GEN-LAST:event_bt_nevacuentaMouseClicked

    private void bt_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ingresarMouseClicked
        // TODO add your handling code here:
        try {
            llenarCuentas1();
            meter.setModal(true);
            meter.pack();
            meter.setLocationRelativeTo(this);
            meter.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_ingresarMouseClicked

    private void bt_mandarPistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mandarPistoMouseClicked
        // TODO add your handling code here:
        try {
            if (jl_cuentas.getSelectedIndex() >= 0) {
                administrarATMs aa = new administrarATMs("./ATMs.atm");
                aa.cargarArchivo();
                if (aa.getAtm().get(cb_atm.getSelectedIndex()).getDen100() < (int) c100.getValue() || aa.getAtm().get(cb_atm.getSelectedIndex()).getDen500() < (int) c500.getValue()) {
                    JOptionPane.showMessageDialog(meter, "Lo sentimos, no hay dinero suficiento");
                } else {
                    AdminUsuarios a = new AdminUsuarios("./Users.u");
                    a.cargarArchivo();
                    int cc = 0;
                    for (int i = 0; i < a.getUsers().size(); i++) {
                        if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                            cc = i;
                        }
                    }
                    ((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas.getSelectedIndex()).setSaldo(((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas.getSelectedIndex()).getSaldo() + (int) c100.getValue() * 100 + (int) c500.getValue() * 500);
                    DateFormat f = new SimpleDateFormat("HH:mm:ss");
                    DateFormat ff = new SimpleDateFormat("dd/MM/YYYY");
                    Date d = new Date();
                    a.getUsers().get(cc).getTransacciones().add(new transacciones(((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas.getSelectedIndex()).getNumeroCuenta(), "Se ingreso un total de: " + ((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas.getSelectedIndex()).getSaldo() + " lps", ff.format(d), f.format(d)));
                    JOptionPane.showMessageDialog(meter, "Transaccion exitosa");
                    meter.setVisible(false);
                    jd_cliente.setVisible(false);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(meter, "Error fatal");
        }
    }//GEN-LAST:event_bt_mandarPistoMouseClicked
    public void estado() {
        AdminUsuarios a = new AdminUsuarios("./Users.u");
        a.cargarArchivo();
        if (a.getUsers().isEmpty()) {

        } else {
            DefaultListModel m = (DefaultListModel) historial.getModel();
            m.removeAllElements();
            for (int i = 0; i < a.getUsers().size(); i++) {
                if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                    for (int j = 0; j < a.getUsers().get(i).getTransacciones().size(); j++) {
                        m.addElement(a.getUsers().get(i).getTransacciones().get(j));
                    }
                }
            }
            historial.setModel(m);
        }
        a.escribirArchivo();
    }
    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            estado();
            jd_transacciones.setModal(true);
            jd_transacciones.pack();
            jd_transacciones.setLocationRelativeTo(this);
            jd_transacciones.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jd_transaccionesWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_transaccionesWindowClosing
        // TODO add your handling code here:
        try {
            jd_transacciones.setVisible(false);
            jd_cliente.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jd_transaccionesWindowClosing

    private void jd_transaccionesWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_transaccionesWindowClosed
        // TODO add your handling code here:
        try {
            jd_transacciones.setVisible(false);
            jd_cliente.setVisible(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jd_transaccionesWindowClosed

    private void bt_revisarsaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_revisarsaldoMouseClicked
        // TODO add your handling code here:
        try {
            llenarCuentas2();
            jd_estado.setModal(true);
            jd_estado.pack();
            jd_estado.setLocationRelativeTo(this);
            jd_estado.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_revisarsaldoMouseClicked
    public void llenarCuentas2() {
        AdminUsuarios a = new AdminUsuarios("./Users.u");
        a.cargarArchivo();
        if (a.getUsers().isEmpty()) {

        } else {
            DefaultListModel m = (DefaultListModel) jl_cuentas1.getModel();
            m.removeAllElements();
            for (int i = 0; i < a.getUsers().size(); i++) {
                if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                    for (int j = 0; j < ((Cliente) a.getUsers().get(i)).getCuentas().size(); j++) {
                        m.addElement(((Cliente) a.getUsers().get(i)).getCuentas().get(j));
                    }
                }
            }
            jl_cuentas1.setModel(m);
        }
        a.escribirArchivo();
    }
    private void versaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versaldoMouseClicked
        // TODO add your handling code here:
        try {
            if (jl_cuentas1.getSelectedIndex() >= 0) {
                AdminUsuarios a = new AdminUsuarios("./Users.u");
                a.cargarArchivo();
                DefaultListModel m = (DefaultListModel) jl_cuentas1.getModel();
                m.removeAllElements();
                int cc = 0, ccc = 0;
                for (int i = 0; i < a.getUsers().size(); i++) {
                    if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                        //for (int j = 0; j < ((Cliente) a.getUsers().get(i)).getCuentas().size(); j++) {
                        cc = i;
                        //  ccc = j;
                        //}
                    }
                }
                JOptionPane.showMessageDialog(jd_estado, "El saldo es: " + Integer.toString((int) ((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas1.getSelectedIndex()).getSaldo()));
                jd_estado.setVisible(false);
                jd_cliente.setVisible(false);
                a.escribirArchivo();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_versaldoMouseClicked
    public void llenarCuentas3() {
        AdminUsuarios a = new AdminUsuarios("./Users.u");
        a.cargarArchivo();
        if (a.getUsers().isEmpty()) {

        } else {
            DefaultListModel m = (DefaultListModel) jl_cuentas2.getModel();
            m.removeAllElements();
            for (int i = 0; i < a.getUsers().size(); i++) {
                if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                    for (int j = 0; j < ((Cliente) a.getUsers().get(i)).getCuentas().size(); j++) {
                        m.addElement(((Cliente) a.getUsers().get(i)).getCuentas().get(j));
                    }
                }
            }
            jl_cuentas2.setModel(m);
        }
        a.escribirArchivo();
    }
    private void bt_retirarPistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_retirarPistoMouseClicked
        // TODO add your handling code here:
        try {
            llenarCuentas3();
            jd_retirar.setModal(true);
            jd_retirar.pack();
            jd_retirar.setLocationRelativeTo(this);
            jd_retirar.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_retirarPistoMouseClicked

    private void bt_mandarPisto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mandarPisto1MouseClicked
        // TODO add your handling code here:
        try {
            if (jl_cuentas2.getSelectedIndex() >= 0) {
                administrarATMs aa = new administrarATMs("./ATMs.atm");
                aa.cargarArchivo();
                if (aa.getAtm().get(cb_atm.getSelectedIndex()).getDen100() < (int) c102.getValue() || aa.getAtm().get(cb_atm.getSelectedIndex()).getDen500() < (int) c501.getValue()) {
                    JOptionPane.showMessageDialog(meter, "Lo sentimos, no hay dinero suficiento");
                } else {
                    AdminUsuarios a = new AdminUsuarios("./Users.u");
                    a.cargarArchivo();
                    int cc = 0;
                    for (int i = 0; i < a.getUsers().size(); i++) {
                        if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                            cc = i;
                        }
                    }
                    ((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas2.getSelectedIndex()).setSaldo(((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas2.getSelectedIndex()).getSaldo() - (int) c102.getValue() * 100 + (int) c501.getValue() * 500);
                    DateFormat f = new SimpleDateFormat("HH:mm:ss");
                    DateFormat ff = new SimpleDateFormat("dd/MM/YYYY");
                    Date d = new Date();
                    a.getUsers().get(cc).getTransacciones().add(new transacciones(((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas2.getSelectedIndex()).getNumeroCuenta(), "Se retiro un total de: " + ((Cliente) a.getUsers().get(cc)).getCuentas().get(jl_cuentas2.getSelectedIndex()).getSaldo() + " lps", ff.format(d), f.format(d)));
                    JOptionPane.showMessageDialog(jd_retirar, "Transaccion exitosa");
                    jd_retirar.setVisible(false);
                    jd_cliente.setVisible(false);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(meter, "Error fatal");
        }
    }//GEN-LAST:event_bt_mandarPisto1MouseClicked
    public void llenarCuentas1() {
        AdminUsuarios a = new AdminUsuarios("./Users.u");
        a.cargarArchivo();
        if (a.getUsers().isEmpty()) {

        } else {
            DefaultListModel m = (DefaultListModel) jl_cuentas.getModel();
            m.removeAllElements();
            for (int i = 0; i < a.getUsers().size(); i++) {
                if (tf_iu.getText().equals(Integer.toString(a.getUsers().get(i).getIduser())) && tf_ip.getText().equals(a.getUsers().get(i).getContraseña())) {
                    for (int j = 0; j < ((Cliente) a.getUsers().get(i)).getCuentas().size(); j++) {
                        m.addElement(((Cliente) a.getUsers().get(i)).getCuentas().get(j));
                    }
                }
            }
            jl_cuentas.setModel(m);
        }
        a.escribirArchivo();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JSpinner b100;
    private javax.swing.JSpinner b100a;
    private javax.swing.JSpinner b500;
    private javax.swing.JSpinner b500a;
    private javax.swing.JButton bt_agregarBishete;
    private javax.swing.JButton bt_atm;
    private javax.swing.JButton bt_c;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_mandarPisto;
    private javax.swing.JButton bt_mandarPisto1;
    private javax.swing.JButton bt_nevacuenta;
    private javax.swing.JButton bt_retirarPisto;
    private javax.swing.JButton bt_revisarsaldo;
    private javax.swing.JButton bt_users;
    private javax.swing.JSpinner c100;
    private javax.swing.JSpinner c101;
    private javax.swing.JSpinner c102;
    private javax.swing.JSpinner c500;
    private javax.swing.JSpinner c501;
    private javax.swing.JComboBox<String> cb_atm;
    private javax.swing.JTextField contra;
    private javax.swing.JButton crearu;
    private com.toedter.calendar.JDateChooser fechaa;
    private com.toedter.calendar.JDateChooser fechan;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JList<String> historial;
    private javax.swing.JTextField id;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_atm;
    private javax.swing.JDialog jd_cliente;
    private javax.swing.JDialog jd_estado;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_mantenimiento;
    private javax.swing.JDialog jd_retirar;
    private javax.swing.JDialog jd_transacciones;
    private javax.swing.JDialog jd_users;
    private javax.swing.JList<String> jl_cuentas;
    private javax.swing.JList<String> jl_cuentas1;
    private javax.swing.JList<String> jl_cuentas2;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JLabel jl_hora1;
    private javax.swing.JSpinner mante;
    private javax.swing.JDialog meter;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JRadioButton rb_cliente;
    private javax.swing.JRadioButton rb_mantenimiento;
    private com.toedter.calendar.JDateChooser tf_fechaATM;
    private javax.swing.JTextField tf_id;
    private javax.swing.JPasswordField tf_ip;
    private javax.swing.JTextField tf_iu;
    private javax.swing.JTextField tf_ubicacion;
    private javax.swing.JButton versaldo;
    // End of variables declaration//GEN-END:variables
    int c = 0;
}
